module.exports = angular.module( 'app.post', [ ])
  .controller('PostController', require('./post.controller'))
  .directive('postView', require('./view.directive'))
  .directive('postEdit', require('./edit.directive'))
  .directive('postSummary', require('./summary.directive'))
  .directive('postArchive', require('./archive.directive'))
